### ISSUE TITLE
All opened requires calling require('fold-cycle').close() two times for each level

### ISSUE THREAD

**Issue by balazser** [jghauser/fold-cycle.nvim#1] opened 2022-05-02 08:26 UTC
Hi @jghauser,
_I use `fold-cycle.nvim` with the default keymapping `TAB` and `S-TAB` in a python project with `LSP`._

Why does [fold-cycle.nvim](https://github.com/jghauser/fold-cycle.nvim) require pressing `S-TAB` two times for folding fully opened methods?

When I have a method full opened and I start to fold it from the bottom by pressing `<S-TAB>` or even calling `lua require('fold-cycle').close()` then for some reason I need to press `S-TAB` two times for every level to get folded.

In the opposite direction, it seems to work. So if I recursively close by calling `open` on a fully opened method and open level by level and then close it back by <S-TAB> seems I need to press <S-TAB> only one time to get the level folded again.

**Comment by jghauser** [comment] 2022-05-05 10:44
Hello and thanks for your interest in this plugin! I'm not entirely sure I understand what the issue is, so tell me if I'm getting something wrong.

You're saying that when a method is fully open and you close it, it doesn't close fully? But when the method is fully open and you open it more, it closes completely? This can happen if the method has two (nested) levels of folding (so one is the method, and another fold may for example be some function inside the method). In that case, closing a fully open method will close the first fold (the function), and the second closing command will close the method. Trying to open such a fully open method would completely close it because by default the config specifies `close_if_max_opened = true`, which means trying to open a fold that is fully open will close it completely.

If this is not what is happening in your case, could you maybe post an example method for which the problem occurs and explain exactly where the cursor is and what the level of folding is when you observe the strange behaviour? Thanks! :)

**Comment by jghauser** [comment] 2022-05-19 07:29
Closing due to lack of response. Feel free to reopen if the issue remains.

**Closed by jghauser** 2022-05-19 07:29 UTC
